config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  # Валидация
  validates :text, presence: true, length: { maximum: 255 }
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new
  FORMAT_USERNAME = /\A\w+\z/
  FORMAT_COLOR = /\A#([\h]{3}){1,2}\z/

  # Виртуальный пароль
  attr_accessor :password

  has_many :questions, dependent: :destroy

  before_validation :username_downcase, if: :username
  before_save :encrypt_password, if: :password

  # Валидация
  validates :username, presence: true,
            uniqueness: true,
            length: {maximum: 40},
            format: {with: FORMAT_USERNAME}

  validates :email, presence: true,
            uniqueness: true,
            format: {with: URI::MailTo::EMAIL_REGEXP}

  validates :password,
            presence: true,
            on: [:create, :destroy],
            confirmation: true

  validates :profilecolor,
            format: { with: FORMAT_COLOR },
            if: :profilecolor

  # Служебный метод, преобразующий бинарную строку в 16-ричный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email) # сперва находим кандитата по email
    # ОБРАТИТЕ ВНИМАНИЕ - сравнивается password_hash, а оригинальный пароль так никогда
    # и нигде не сохраняется!
    if user.present? && user.password_hash == User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  private

  def encrypt_password
    if self.password.present?
      # создаем т.н. "соль" - рандомная строка, усложняющая задачу хакерам
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      # создаем хэш пароля - длинная уникальная строка, из которой невозможно
      # восстановить исходный пароль
      self.password_hash = User.hash_to_string(
          OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST))
    end
  end

  def username_downcase
    self.username = username.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вы не имеете прав для доступа!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)

    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос удачно создан!'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен!'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален!'
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer, :author_id)
    else
      params.require(:question).permit(:user_id, :text, :author_id)
    end
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])

    if @user.present?
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Вы вошли на сайт!'
    else
      flash.now.alert = 'Неправильный логин или пароль!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы вышли! Приходите ещё!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :new, :create]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_path, alert: 'Вы уже есть на сайте!' if current_user.present?
    @user = User.new
  end

  def edit
  end

  def create
    redirect_to root_path, alert: 'Вы уже есть на сайте!' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @with_answer_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @with_answer_count
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    flash[:success] = "Пользователь удален."
    redirect_to root_path
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation,
                                 :name, :username, :avatar_url, :profilecolor, :profileimg)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def inclination(num, singular, singular_rod, plural_rod)
    modul = num % 10
    modul_2 = num % 100

    if (11..14).cover?(modul_2)
      return plural_rod
    elsif modul == 1
      return singular
    elsif (2..4).cover?(modul)
      return singular_rod
    else
      return plural_rod
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def author_questions(question, stranger)
    if question.author.present?
      link_to(question.author&.username, user_path(question.author))
    else
      stranger
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>

<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %>
        <%= '|||' %>
        <%= link_to 'Выйти', session_path, data: {method: :delete} %>
      <% else %>
        <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash_#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "Вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>


<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
    <div class="question-text text-lead">
      <div class="buffer-top mini-text">
        Этот вопрос от:
      </div>
      <div class="author">
      <%= author_questions(question, "Незнакомец") %>
    </div>
  </div>
</div>

<% if question.user == current_user %>
  <div class="question-actions">
    <%= link_to fa_icon(action_icon), edit_question_path(question) %>
    <%= link_to fa_icon('trash-o'), question_path(question),
                method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
  </div>
<% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Редактировать профиль</h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label 'Ваш никнейм:', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя:', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки:', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label 'Пароль:', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Пароль еще раз:', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-field buffer-top">
        <%= f.label 'Изменить цвет профиля:', class: 'form-label' %>
        <%= f.color_field :profilecolor, value: "#{@user.profilecolor}", class: 'color-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL фоновой картинки для профиля:', class: 'form-label' %>
        <%= f.text_field :profileimg, value: "#{@user.profileimg}", class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small button-left' %>
      </div>

      <div class="buffer-both">
        <%= link_to "Удалить профиль", @user,class: 'button button-red button-small button-right', method: :delete,
                    data: { confirm: "Вы уверены?"} if current_user == @user %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%# Пользуемся аж тремя хелперами %>
        <%# link_to — генерирует ссылку %>
        <%# image_tag — генерирует картинку %>
        <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
        <%# Хелпер user_path(user) возвращает относительный путь %>
        <%# страницы пользователя, например /users/1 %>
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
      <div class="buffer-bottom-user">
        <p class="username">
          @<%= user.username %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>

      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div style="background: url(<%= @user.profileimg %>)no-repeat fixed center / cover;
    background-color: <%= @user.profilecolor %>;" class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: 'Foto' %>
  </div>

  <div class="buffer-top-large  button button-glass">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user%>
  </div>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id="ask-form">
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <%= recaptcha_tags size: 'compact' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">

    <div class="text-center">
      <%= @questions_count %>
      <%= inclination(@questions_count, 'вопрос', 'вопроса', 'вопросов') %>
    </div>

    <div class="text-center">
      С ответом - <%= @with_answer_count %>
      <%= inclination(@with_answer_count, 'вопрос', 'вопроса', 'вопросов') %>
    </div>

    <div class="text-center">
      Без ответа - <%= @unanswered_count %>
      <%= inclination(@unanswered_count, 'вопрос', 'вопроса', 'вопросов') %>
    </div>

    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>